# Generated by Django 4.0.1 on 2022-02-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_catergory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
    ]
