# Generated by Django 4.0.1 on 2022-02-08 12:35

from django.db import migrations, models
import django.db.models.deletion
import myblogapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0003_rename_catergory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=myblogapp.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='myblogapp.category'),
        ),
    ]
