# Generated by Django 4.0.1 on 2022-02-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0009_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
